# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20161217_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['position'], 'verbose_name': 'Element', 'verbose_name_plural': 'Elements'},
        ),
        migrations.AddField(
            model_name='element',
            name='position',
            field=models.SmallIntegerField(default=0, verbose_name='Position'),
        ),
    ]
