language: python
python:
- "3.5"
cache: pip
install: 
  - pip install -r requirements/dev.txt
  - sudo apt-get install -y python-gdal postgresql-9.5-postgis-2.3
  - psql -U postgres -c "create extension postgis"
script: py.test --cov=watchdog_kj_kultura


after_success:
  - coveralls

dist: trusty
sudo: required
addons:
  postgresql: "9.5"
