# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 18:40
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djgeojson.fields
import model_utils.fields
import watchdog_kj_kultura.organizations.validators


class Migration(migrations.Migration):

    replaces = [('organizations', '0001_initial'), ('organizations', '0002_auto_20161210_1948'), ('organizations', '0003_auto_20161210_2136'), ('organizations', '0004_organization_pos'), ('organizations', '0005_organization_visible'), ('organizations', '0006_auto_20161222_0252'), ('organizations', '0007_auto_20161230_1852')]

    dependencies = [
        ('teryt_tree', '0002_auto_20151216_0201'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('key', models.CharField(max_length=25, verbose_name='Key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'verbose_name_plural': 'MetaCategorys',
                'verbose_name': 'MetaCategory',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Slug')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Metadata')),
                ('jst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teryt_tree.JednostkaAdministracyjna', verbose_name='Unit of administrative division')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'verbose_name_plural': 'Organizations',
                'verbose_name': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Slug')),
            ],
            options={
                'ordering': ['created'],
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.AlterModelOptions(
            name='metacategory',
            options={'ordering': ['pk'], 'verbose_name': 'MetaCategory', 'verbose_name_plural': 'MetaCategorys'},
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='organization',
            name='pos',
            field=djgeojson.fields.PointField(blank=True, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='organization',
            name='visible',
            field=models.BooleanField(default=False, help_text='Check to mark organization as public visible', verbose_name='Public visible'),
        ),
        migrations.AlterField(
            model_name='metacategory',
            name='key',
            field=models.CharField(help_text='They are permitted only Latin characters and numbers.', max_length=25, validators=[watchdog_kj_kultura.organizations.validators.is_allnum], verbose_name='Key'),
        ),
    ]
