# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 18:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Metadata'),
        ),
    ]
