# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 02:19
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20161210_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='pos',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, null=True, srid=4326, verbose_name='Position'),
        ),
    ]
