# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='visible',
            field=models.BooleanField(default=False, help_text='Check to mark organization as public visible', verbose_name='Public visible'),
        ),
    ]
