# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_metacategory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metacategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
