# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 17:52
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Organization = apps.get_model("organizations", "Organization")
    db_alias = schema_editor.connection.alias
    Organization.objects.using(db_alias).update(pos=None)


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20161222_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='pos',
            field=djgeojson.fields.PointField(blank=True, null=True, verbose_name='Position'),
        ),
        migrations.RunPython(forwards_func),
    ]
