# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 04:38
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import watchdog_kj_kultura.organizations_requests.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_organization_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('delta', watchdog_kj_kultura.organizations_requests.fields.RelativeDeltaField(help_text='Try to write words a period of time.', max_length=50, verbose_name='The period for sending notification')),
                ('subject', models.CharField(help_text='Supported is some shortcodes. Refer to the documentation.', max_length=100, verbose_name='Subject of notification')),
                ('body', models.TextField(help_text='Supported is some shortcodes. Refer to the documentation.', verbose_name='Body of notification')),
            ],
            options={
                'verbose_name_plural': 'Notification',
                'ordering': ['template_id'],
                'verbose_name': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('email', models.EmailField(max_length=254, verbose_name='Email of organization')),
                ('email_user', models.EmailField(help_text='E-mail is necessary for security purposes, as well as notification of the request.', max_length=254, verbose_name='E-mail')),
                ('body', models.TextField(verbose_name='Content of the request')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name_plural': 'Requests',
                'ordering': ['created'],
                'verbose_name': 'Request',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Slug')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
                ('email_required', models.BooleanField(help_text='Mark to require email in content of request')),
                ('visible', models.BooleanField(default=True, help_text='Check to mark template as public visible', verbose_name='Public visible')),
            ],
            options={
                'verbose_name_plural': 'Templates',
                'ordering': ['created'],
                'verbose_name': 'Template',
            },
        ),
        migrations.AddField(
            model_name='request',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations_requests.Template', verbose_name='Used templates'),
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations_requests.Template', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='event',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations_requests.Notification', verbose_name='Notification'),
        ),
        migrations.AddField(
            model_name='event',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations_requests.Request', verbose_name='Request'),
        ),
    ]
