# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='email_required',
            field=models.BooleanField(help_text='Mark to require email in content of request', verbose_name='Require email'),
        ),
    ]
