# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_requests', '0003_template_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.TextField(default='', help_text='Short description of the potential use of the template.', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
