# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='visible',
            field=models.BooleanField(default=False, help_text='Check to mark page as public visible', verbose_name='Public visible'),
        ),
    ]
