# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 04:16
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0002_page_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='staticpages.Page', verbose_name='Parent'),
        ),
    ]
