# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import tinymce.models
from django.conf import settings


def create_settings_forward(apps, schema_editor):
    """Create a initial Settings"""
    Settings = apps.get_model('main', 'Settings')
    Settings.objects.update_or_create(
        site_id=settings.SITE_ID,
        defaults={
            'home_content': 'kultura.kj.org.pl',
        }
    )


def remove_settings_backward(apps, schema_editor):
    """Remove settings object previously created."""
    Settings = apps.get_model('main', 'Settings')
    Settings.objects.filter(site_id=settings.SITE_ID).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0003_set_site_domain_and_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now,
                                                                editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now,
                    editable=False,
                    verbose_name='modified')),
                ('home_content', tinymce.models.HTMLField(verbose_name='Content of home page')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              to='sites.Site',
                                              verbose_name='Site')),
            ],
            options={
                'verbose_name_plural': 'Settings',
                'verbose_name': 'Settings',
                'ordering': ['created'],
            },
        ),
        migrations.RunPython(create_settings_forward, remove_settings_backward),
    ]
