# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161211_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_about_fix',
            field=models.BooleanField(default=False, help_text='Check to receive notifications about fix suggestion to organization description', verbose_name='Notify about fix suggestion to organization'),
        ),
    ]
